[build]
  publish = "."
  command = "echo 'No build needed'"

# Form handling for newsletter signups
[build.processing]
  skip_processing = false

# Clean URL redirects (optional - for prettier URLs)
[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/tools"
  to = "/tools.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

# Handle admin routes for Netlify CMS
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# 404 handling - serve a custom 404 page if you create one
# [[redirects]]
#   from = "/*"
#   to = "/404.html"
#   status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
